#!/bin/sh

# Make sure git is installed to download custom repo
pacman --needed --noconfirm -Sy git

# Download custom repo
git clone https://www.github.com/LordRusk/rskrepo ~/rskrepo
cat /etc/pacman.conf ~/sai/customrepo > /etc/pacman.conff
cp /etc/pacman.conff /etc/pacman.conf
  
# Install needed script packages
pacman --noconfirm --needed -Sy dash neovim slmenu

# Start the real script
dash ~/sai/sai2
