#!/bin/sh

# Make sure git is installed to download custom repo
pacman --needed --noconfirm -Sy git

# Download custom repo
git clone https://www.github.com/LordRusk/rskrepo ~/
cat customrepo > /etc/pacman.conf
  
# Install needed script packages
pacman --noconfirm --needed -Sy neovim slmenu

# Start the real script
dash ~/sai/sai2
