#!/bin/dash

### FUNCTIONS ###

error() { printf "Spomething went wrong, maybe it was you, maybe it was the script, who knows"; exit; }

nxt() { echo "Next" | slmenu -p "Continue?"; }

xit() {
	xon=$(echo "Continue\nExit" | slmenu -i -p "$xprompt")
	if [ "$xom" = "exit" ]; then
		echo "Exited..."
		exit
	fi
}

welcome() {
	clear
	echo "Welcome to SAI (Simple Arch Install)"
	echo "This script is to help you get arch installed fast, efficently, and meet any needs you may have."
	xprompt="Continue?"
	xit
}

formatdrive() {
	clear
	echo "Are are installing arch on a non EFI bios or a EFI bios."
	bs=$(echo "non EFI\nEFI" | slmenu -p "non EFI or EFI")

	clear
	echo "Would you like to nuke the drive and install a completely fresh arch install, or configure your own partitions?"
	auto=$(echo "Nuke partitions\nConfigure partitions" | slmenu -l 2 -p "Configure the partitions or nuke and auto reinstall?")
	if [ "$auto" = "Configure partitions" ]; then
		clear
		if [ "$bs" = "non EFI" ]; then
			echo "If you're going to (re)install grub, mount your boot partition at /mnt/boot"
		elif [ "$bs" = "EFI" ]; then
			echo "If you're going to (re)install grub, mount your boot partition at /mnt/boot/efi"
		fi
		echo "General rule of thumb, root partition is mounted at /mnt"
		echo "and home pertition (if you have one) is mounted at /mnt/home"
		sh
		wait
		
		clear
		echo "Please select the drive to install arch on"
		sdrive=$(lsblk -lp | grep "disk $" | awk '{print $1, "(" $4 ")"}' | slmenu -i -p "Choose a drive")
		cdrive=$(echo "$sdrive" | awk '{print $1}')
	elif [ "$auto" = "Nuke partitions" ]; then
		clear
		echo "Please select the drive you would like to install arch on"
		sdrive=$(lsblk -lp | grep "disk $" | awk '{print $1, "(" $4 ")"}' | slmenu -i -p "Choose a drive")
		cdrive=$(echo "$sdrive" | awk '{print $1}')

		clear
		echo "How big do you want your root partition to be? Defualt is 20gb"
		rps=$(echo "20gb" | slmenu -i -p "Size of root partition")

		clear
		echo "How big do you want your swap partition? Defualt is 1.5x your ram"
		sps=$(echo "" | slmenu -i -p "Size of swap partition")

		clear
		echo "If you continue, the selected drive will be wiped, all data will be lost, do you want to continue?"
		xprompt="Are you sure you want to continue?"
		xit

		dd if=/dev/zero of="$cdrive"  bs=512  count=1
		if [ $bs = EFI ]; then
			echo "g\nn\n\n\n+500mb\nn\n\n\n+"$sps"\nn\n\n\n+"$rps"\nn\n\n\n\nw" | fdisk "$cdrive"
		else
			echo "n\np\n\n\n+500mb\nn\np\n\n\n+"$sps"\nn\np\n\n\n+"$rps"\nn\np\n\n\n\nw" | fdisk "$cdrive"
		fi
		mkfs.ext4 "$cdrive"3
		mkfs.ext4 "$cdrive"4
		mount "$cdrive"3 /mnt
		mkdir /mnt/home
		mount "$cdrive"4 /mnt/home
		mkdir /mnt/boot
		if [ "$bs" = "EFI" ]; then
			mkdir /mnt/boot/efi
			mkfs.fat -F32 "$cdrive"1
			mount "$cdrive"1 /mnt/boot/efi
		else
			mkfs.ext4 "$cdrive"1
			mount "$cdrive"1 /mnt/boot
		fi
		mkswap "$cdrive"2
		swapon "$cdrive"2
	fi
}

mirrorlist() {
	clear
	echo "The defualt arch mirrorlist can be slow and unreliable, please edit the mirrorlist for faster speeds"
	nxt
	nvim /etc/pacman.d/mirrorlist
}

install() {
	clear
	pacstrap /mnt base linux linux-firmware pacman slmenu dash neovim
}

postinstall() {
	genfstab -U /mnt >> /mnt/etc/fstab

	echo "$cdrive\n$auto" > /mnt/temp

	cp ~/sai/sai3 /mnt
	arch-chroot /mnt dash /sai3

	rm /mnt/sai3
	rm /mnt/temp

	clear
	echo "SAI has finished, you would you like to reboot?"
	rb=$(echo "Reboot\nDon't Reboot" | slmenu -p "Would you like to reboot now?")
	if [ "$rb" = "Reboot" ]; then
		reboot
	fi
}


### THE ACTUAL SCRIPT ###

# Welcome the user
welcome || error

# Everything that must be done to the drives
formatdrive || error

# Edit the mirrorlist for faster downloads
mirrorlist || error

# The actual install
install || error

# Launch lpi3.sh, then delete the files from /mnt after
postinstall || error
